---
- name: Generate random password
  ansible.builtin.set_fact:
    new_password: "{{ lookup('community.general.random_string', length=12, special=false) }}"

- name: Change password for user {{ item }}
  ansible.windows.win_user:
    name: "{{ item }}"
    password: "{{ new_password }}"

- name: Export password changes to CSV
  community.windows.win_lineinfile:
    path: "{{ ntlmpasswordfile.path }}"
    line: "{{ item }},{{ new_password }}"
  when: "'new_password' is defined"
