---
- name: Generate random password for {{ item.Name }}
  ansible.builtin.set_fact:
    new_password: "{{ lookup('community.general.random_string', length=12, special=false) }}"

- name: Print {{ item.Name }}
  ansible.builtin.debug:
    var: item

- name: Print sid
  ansible.builtin.debug:
    msg: "{{ item.ObjectGUID }}"

- name: Change AD password for {{ item.Name }}
  microsoft.ad.user:
    name: "{{ item.Name }}"
    identity: "{{ item.ObjectGUID }}"
    password: "{{ new_password }}"


- name: Export password of {{ item.Name }}
  ansible.builtin.win_lineinfile:
    path: "{{ adpasswordfile.path }}"
    line: "{{ item.Name }},{{ new_password }}"
