---
# See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/iptables_module.html  
  
  - name: Disable firewall services
    service:
      name: "{{ item }}"
      enabled: no
      state: stopped
    loop: "{{ firewall_services }}"

  - name: Flush all iptables rules
    iptables:
      chain: ALL
      flush: yes

  - name: Set default forward policy to DENY
    iptables:
      chain: FORWARD
      policy: DENY

  - name: open ssh?
    iptables: 
      chain: INPUT
      destination_port: "sshd"
      jump: accept

  - name: Set default input chain policy to ACCEPT
    iptables:
      chain: INPUT
      policy: ACCEPT

  - name: Set default output chain policy to ACCEPT
    iptables:
      chain: OUTPUT
      policy: ACCEPT