---
- name: Provision debian VM
  become: true  # If you need to run tasks with elevated privileges, such as sudo
  hosts: all
  gather_facts: true

  tasks:
    - name: Install docker
      ansible.builtin.apt:
        update_cache: true
        name: docker.io
    - name: Add vagrant user to sudo
      ansible.builtin.user:
        name: vagrant
        append: true
        groups: sudo  # Add the user to the sudo group
    - name: Create Wheel group
      ansible.builtin.group:
        name: wheel
        state: present
    - name: Create Example User
      ansible.builtin.user:
        name: example_user
        comment: "Example User"
        groups: ["wheel", "sudo", "docker", "adm"] # Add the user to the wheel group
        createhome: true
        shell: /bin/bash
