mysql_backup_version: "" # Backup version, string

mysql_backup: false # Set to true to backup, but don't bother with this. Stop the service and use the "backup" role to manage the mysql directory instead.


mysql_user: "root" # User to log into the database of

mysql_password: # Password of the mysql root user

mysql_host: "localhost" # Host to connect to.



mysql_port: 3306

mysql_shuffle_passwords: false # Set to true to shuffle all passwords. 


# Workaround for a conditional become, where it fails to evaluate inventory_hostname against a string, as it attempts to evaluate the stirng as a variable.
localhost: "localhost" 