---
- name: Centos testing playbook
  become: true  # If you need to run tasks with elevated privileges, such as sudo
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

  roles:
    - name: logindefs
      tags: logindefs
    - name: pwquality
      tags: pwquality
    - name: nix
    - name: sshd
      vars:
        sshd_nixify: true
      tags: sshd
    - name: apt
      when: not ansible.builtin.stat(path='/etc/apt.bac').stat.exists
