---

- name:
  become: true  # If you need to run tasks with elevated privileges, such as sudo
  hosts: all
  gather_facts: true

  roles:
    - name: logindefs
      tags: logindefs
    - name: pwquality
      tags: pwquality
    - name: nix
    - name: sshd
      vars:
        # sshd_only_user = administrator ? # for if we want to deny all other users access to sshd.
      tags: sshd
    # - name: apt
    #   tags: apt
    #   when: not ansible.builtin.stat(path='/etc/apt.bac').stat.exists
