---
- name: Backup apt sources
  ansible.builtin.copy:
    src: /etc/apt/
    dest: /etc/apt.bac/
    owner: root
    group: root
    mode: '0644'

- name: Remove apt sources
  ansible.builtin.file:
    path: /etc/apt/
    state: absent
- name: Put new ansible files in the correct spot
  ansible.builtin.copy:
    src: templates/{{ ansible_facts['distribution_release'] }}/
    dest: /etc/apt/
    owner: root
    group: root
    mode: '0644'


- name: Use apt to update the system
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe # or do I want to use full, which upgrades everything to the latest versions?
