---

keycloak_tls: "http" # Or https for when that is used

keycloak_server: ""

keycloak_realm: "master" # Realm of keycloak

keycloak_user: "admin"

keycloak_password: "password"

keycloak_passwords_shuffle: false

