# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    #config.vm.provision "shell", path: "provision.sh"

    config.vm.define "12" do |vmconfig|
        #vmconfig.vm.provision "shell", path: "provision.sh"
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/provision.yml"
        end
        vmconfig.vm.box = "debian/bookworm64"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            override.vm.box = "generic/debian12"
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end
    end
end
