---

- name: Update some or all docker containers
  become: true
  when: docker_update_docker_container is defined
  community.docker.docker_container:
    name: watchtower
    image: docker.io/containrrr/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "--run-once {{ docker_containers_to_be_updated | join(' ') }}"


- name: Debug test
  ansible.builtin.debug:
  var:
    docker_containers_to_be_updated