# Watchtower docker container updater
docker_update: false # whether or not to update docker containers
docker_update_containers: [] # By default, watchtower updates all containers. This causes it to only update a few. This is a list


docker_backup_version: "" # A simple version control, use a string.
docker_backup_containers: [] # String of containers to backup.

docker_restore_containers: [] # List of docker containers, this will load their images in the format 'container:docker_backup_version'

# This will also attempt to launch the docker containers using saved compose files.
# This requires the docker python library and probably won't work anyways
docker_restore_compose: false


docker_backup_volumes: [] # List of volumes to back up

docker_restore_volumes: [] # List of docker volumes to restore. 
