Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    #config.vm.provision "shell", path: "provision.sh"

    config.vm.define "bookworm" do |vmconfig|
        #vmconfig.vm.provision "shell", path: "provision.sh"
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/provision.yml"
        end
        vmconfig.vm.box = "generic/dragonflybsd6"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
    end
end
