---
- name: Check if backup directories exists already
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/backups"
  register: backups_dir_created
  # ignore_errors: true # Do I need this option?

- name: Archive and fetch directories
  when: backup_directories is defined
  block:
    # Gitignore part can probably be merged into a single task
    # Also a when statement, for when it's not needed.
    - name: Create .gitignore file
      become: true
      ansible.builtin.template:
        src: templates/gitignore.j2
        dest: /tmp/gitignore
        mode: '0644'
    - name: Fetch gitignore
      ansible.builtin.fetch:
        src: /tmp/gitignore
        dest: "{{ playbook_dir }}/backups/.gitignore"
        flat: yes
    - name: Delete gitignore
      become: true
      ansible.builtin.file:
        path: /tmp/gitignore
        state: absent

    - name: Create archive of declared directories
      become: true
      when: backup_directories is defined
      community.general.archive:
        path: "{{ item }}"
        dest: "/{{ item | replace('/', '_') }}.tar.gz"
        mode: '0644'
      loop: "{{ backup_directories }}"

    - name: Fetch backed up directories
      become: true # This shouldn't need become, but just in case
      ansible.builtin.fetch:
        src: "/{{ item | replace('/', '_') }}.tar.gz"
        dest: "{{ playbook_dir }}/backups/{{ ansible_facts['nodename'] }}/"
        flat: yes
      loop: "{{ backup_directories }}"

    - name: Delete backup on system
      become: true
      ansible.builtin.file:
        state: absent
        path: "/{{ item | replace('/', '_') }}.tar.gz"
      loop: "{{ backup_directories }}"
