---
- name: Generate random password
  ansible.builtin.set_fact:
  vars:
    # chars= here is set to the default, but this needs to be checked if the scoring engine likes these characters
    new_password: "{{ lookup('ansible.builtin.password', '/tmp/passwordfile', length=8, chars=['ascii_letters', 'digits', ''.,:-_']) }}"
    new_password_hashed: ""
- name: Change UNIX passwords for all users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ 'new_password' | password_hash(linux_users_passwords_hash) }}"  
- name: Export password changes to CSV
  ansible.builtin.lineinfile:
    path: "/users.csv"
    line: "{{ item.name }}={{ 'new_password' | password_hash('sha512') }}"
  with_items: "{{ all_users.entries }}"
  when: "'new_password' is defined"
