# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "debian/bookworm64"

  config.vm.define "debian_12" do |vm|
    
    # Specify the box for the VirtualBox provider
    vm.vm.provider :libvirt do |vbox|
      libvirt.memory = 1024
      libvirt.cpus = 1
      libvirt.box = "debian/bookworm64"
      libvirt.video_type = "virtio"
    end
  end

  # config.vm.provider :libvirt do |libvirt|
  #   # Libvirt specific configuration
  #   libvirt.driver = "kvm"  # Use KVM as the hypervisor
  #   #libvirt.host = "localhost"  # Libvirt server address
  #   #libvirt.connect_via_ssh = false  # Connect directly to libvirt without SSH
  #   libvirt.storage_pool_name = "default"  # Replace with your storage pool name
  #   libvirt.memory = 1024  # Set the VM memory size in megabytes
  #   libvirt.cpus = 1  # Set the number of virtual CPUs
  #   libvirt.video_type = "virtio"
  #   libvirt.box = "debian/bookworm64"
  # end
end
