---
# - name: Gather facts
#   ansible.builtin.setup:

- name: Set ansible connection variable
  ansible.builtin.set_fact:
    control_node_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"

- name: Print ansible connection
  ansible.builtin.debug:
    var: control_node_ip


- name: Is docker installed?
  ansible.builtin.command: "docker --version"
  register: docker_installed_command
  ignore_errors: true
  changed_when: false

- name: Docker installed fact
  ansible.builtin.set_fact:
    docker_installed: "{{ not docker_installed_command.failed }}"

- name: Print if docker is installed
  ansible.builtin.debug:
    var: docker_installed

- name: Ansible set facts
  ansible.builtin.set_fact:
    hostname: "{{ ansible_facts['nodename'] }}"
    distro: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
    operating_system: "{{ ansible_facts['system'] }}"
    service_manager: "{{ ansible_facts['service_mgr'] }}"
    cpus: "{{ ansible_processor_count }} of {{ ansible_processor }}"
    memory_total: "{{ ansible_facts['memtotal_mb'] }}"
    # Below is free memory, not including cached stuff
    # TODO: Figure out how to get equivalent of linux  available memory on bsd type systems.
    memory_free: "{{ ansible_memfree_mb }}"

- name: Print relevant facts from ansible facts
  ansible.builtin.debug:
    msg:
      - "hostname: {{ hostname }}"
      - "distro: {{ distro }}"
      - "operating_system: {{ operating_system }}"
      - "service_manager: {{ service_manager }}"
      - "memory_total (megabytes): {{ memory_total }}"
      - "memory_free (megabytes): {{ memory_free }}"
      - "cpus: {{ cpus }}"
