---
# - name: Gather facts
#   ansible.builtin.setup:

- name: Set ansible connection variable
  ansible.builtin.set_fact:
    control_node_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"

- name: Print ansible connection
  ansible.builtin.debug:
    var: control_node_ip


- name: Is docker installed?
  ansible.builtin.command: "docker --version"
  register: docker_installed_command
  ignore_errors: true
  changed_when: false

- name: Docker installed fact
  ansible.builtin.set_fact:
    docker_installed: "{{ not docker_installed_command.failed }}"

- name: Print if docker is installed
  ansible.builtin.debug:
    var: docker_installed

- name: Ansible set facts
  ansible.builtin.set_fact:
    hostname: "{{ ansible_facts['nodename'] }}"
    operating_system: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
    service_manager: "{{ ansible_facts['service_mgr'] }}"
    memory_total: "{{ ansible_facts['memtotal_mb'] }}"
    #memory_free: "{{ ansible_facts['memory_mb']['nocache']['free'] }}" # Does not exist on dragonflybsd. 

- name: Print relevant facts from ansible facts
  ansible.builtin.debug:
    msg:
      - "hostname: {{ hostname }}"
      - "operating_system: {{ operating_system }}"
      - "service_manager: {{ service_manager }}"
      - "memory_total (megabytes): {{ memory_total }}"
