---

- name: Print ansible_connection
  ansible.builtin.debug:
    msg: "{{ ansible_env['SSH_CLIENT'].split() | first }}"

- name: Set ansible connection variable
  ansible.builtin.set_fact:
    control_node_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"

- name: Print ansible connection
  ansible.builtin.debug:
    var: control_node_ip


- name: Is docker installed?
  ansible.builtin.command: "docker --version"
  register: docker_installed_command
  ignore_errors: true
  changed_when: docker_installed_command.rc != 0

- name: Docker installed fact
  ansible.builtin.set_fact:
    docker_installed: "{{ not docker_installed_command.failed }}"

- name: Print if docker is installed
  ansible.builtin.debug:
    var: docker_installed
