# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    #config.vm.provision "shell", path: "provision.sh"

    config.vm.define "focal" do |vmconfig|
        # Basically focal, but with a webshell installed as well.
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/webshell.yml"
        end
        vmconfig.vm.box = "generic/ubuntu2004"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end
        
    end
end
