---
- name: Generate random password for {{ item.key }}
  ansible.builtin.set_fact:
    new_password: "{{ lookup('community.general.random_string', length=12, special=false) }}"

- name: Change postgres password for {{ item.key }}
  community.postgresql.postgresql_user:
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    login_port: "{{ postgres_port }}"
    user: "{{ item.key }}"
    password: "{{ new_password }}"

- name: Export password of {{ item.key }}
  ansible.builtin.lineinfile:
    path: "/tmp/{{ postgrespasswords }}"
    line: "{{ item.key }},{{ new_password }}"
