---
# To get list of users?
# From chatgpt
- name: Get List of Keycloak Users
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Retrieve Keycloak access token
      uri:
        url: "http://your-keycloak-server/auth/realms/your-realm/protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          username: "admin-user"
          password: "admin-password"
          grant_type: "password"
          client_id: "admin-cli"
      register: keycloak_token
- name: Retrieve list of Keycloak users
  uri:
    url: "http://your-keycloak-server/auth/admin/realms/your-realm/users"
    method: GET
    headers:
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
  register: keycloak_users

- name: Display Keycloak users
  debug:
    var: keycloak_users.json


# To change users
# https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_user_module.html#ansible-collections-community-general-keycloak-user-module