---
- name: Generate random password
  ansible.builtin.set_fact:
    new_password: "{{ lookup('community.general.random_string', length=12, special=false) }}"
- name: Change password of {{ userinfo.username }} for realm {{ item.get('realm') }}
  community.general.keycloak_user:
    auth_keycloak_url: "{{ keycloak_tls }}://{{ keycloak_server }}/"
    auth_username: "{{ keycloak_user }}"
    auth_password: "{{ keycloak_password }}"
    auth_realm: "{{ keycloak_admin_realm }}"
    realm: "{{ item.get('realm') }}"
    username: "{{ userinfo.username }}"
    credentials:
      - type: password
        value: "{{ new_password }}"
        temporary: false
    force: true # Does this delete existing data like attributes, name, and email?
    state: present
- name: Export password changes to CSV
  ansible.builtin.lineinfile:
    path: "/tmp/{{ keycloakpasswords }}"
    line: "{{ userinfo.username }},{{ new_password }}"
  when: "'new_password' is defined"
