# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true
  #config.vm.provision "shell", path: "provision.sh"

  config.vm.box = "valengus/windows10-22h2-x64"

  config.vm.provider "libvirt" do |libvirt, override|
    override.vm.box = "valengus/windows10-22h2-x64"
    libvirt.driver = "kvm"
    libvirt.memory = 6
    libvirt.cpus = 2
    libvirt.video_type = "virtio"
    libvirt.graphics_type = "vnc"
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :disabled => true
  end



  # config.vm.define "libvirt" do |libvirt|
  #   libvirt.vm.box = "valengus/windows10-22h2-x64"
  #   libivrt.vm.provider = "libvirt" do |lb|
  #     lb.driver = "kvm"
  #     lb.memory = 6
  #     lb.cpus = 2
  #     lb.video_type = "virtio"
  #   end
  # end
  # config.vm.box = "valengus/windows10-22h2-x64"
  # config.vm.provider :libvirt do |libvirt|
  #   # Libvirt specific configuration
  #   libvirt.driver = "kvm"  # Use KVM as the hypervisor
  #   libvirt.memory = 6  # Set the VM memory size in megabytes
  #   libvirt.cpus = 2  # Set the number of virtual CPUs
  #   libvirt.video_type = "virtio"
  # end
end

