---
- name: Generate random password
  ansible.builtin.set_fact:
    # Specials is false here to ensure maximum compatibility with scoring engine.
    new_password: "{{ lookup('community.general.random_string', length=12, special=false) }}"
    # new_password_hashed: ""
- name: Change password for user {{ item }}
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ new_password | password_hash(users_passwords_hash) }}"

# Delegate to localhost to avoid plaintext passwords from getting out.
# Or store in a hard to find file in /tmp
- name: Export password changes to CSV
  ansible.builtin.lineinfile:
    path: "/tmp/{{ passwordlistfile }}"
    line: "{{ item }},{{ new_password }}"
  when: "'new_password' is defined"
