---


# TODO: Only have it generate passwords for users that already have a password, right now it generates for every users
- name: Shuffle passwd user passwords
  become: true
  when: users_passwords_shuffle
  block:
    # Below part can probably be merged into a single task somehow.
    # Also a when statement, for when it's not needed.
    - name: Create gitignore
      become: true
      ansible.builtin.template:
        src: templates/gitignore.j2
        dest: /tmp/gitignore
        mode: '0644'
    - name: Fetch gitignore
      ansible.builtin.fetch:
        src: /tmp/gitignore
        dest: "{{ playbook_dir }}/passwords/.gitignore"
        flat: yes
    - name: Delete gitignore file from server
      become: true
      ansible.builtin.file:
        path: /tmp/gitignore
        state: absent
  
    - name: Get human users
      ansible.builtin.getent:
        database: passwd
      register: passwd

    # Parse this to only do human users or something because this sucks.

    - name: Create random location for passwords csv
      ansible.builtin.set_fact:
        passwordlistfile: "{{ lookup('community.general.random_string', length=12, special=false) }}"
    - name: Create scoring engine CSV
      ansible.builtin.file:
        dest: "/tmp/{{ passwordlistfile }}"
        mode: '0644'
        state: touch

    - name: Loop through users, change passwords
      ansible.builtin.include_tasks:
        file: tasks/change_passwords.yml
      loop: "{{ passwd.ansible_facts.getent_passwd | dict2items | map(attribute='key') | list }}"

    - name: Fetch passwordlist
      ansible.builtin.fetch:
        src: "/tmp/{{ passwordlistfile }}"
        dest: "{{ playbook_dir }}/passwords/{{ ansible_facts['nodename'] }}/passwordlist.csv"
        flat: yes

    - name: Delete passwordlist
      ansible.builtin.file:
        path: "/tmp/{{ passwordlistfile }}"
        state: absent
