---
- name: Get human users
  become: true
  ansible.builtin.getent:
    database: passwd
  register: passwd

- name: Get groups
  become: true
  ansible.builtin.getent:
    database: group


# TODO: Only have it generate passwords for users that already have a password, right now it generates for every users
- name: Shuffle passwd user passwords
  become: true
  when: users_passwords_shuffle
  block:
    # Below part can probably be merged into a single task somehow.
    # Also a when statement, for when it's not needed.
    - name: Create gitignore
      become: true
      ansible.builtin.template:
        src: templates/gitignore.j2
        dest: /tmp/gitignore
        mode: '0644'
    - name: Fetch gitignore
      ansible.builtin.fetch:
        src: /tmp/gitignore
        dest: "{{ playbook_dir }}/passwords/.gitignore"
        flat: true
    - name: Delete gitignore file from server
      become: true
      ansible.builtin.file:
        path: /tmp/gitignore
        state: absent
    # Parse this to only do human users or something because this sucks.

    - name: Create random location for passwords csv
      ansible.builtin.set_fact:
        passwordlistfile: "{{ lookup('community.general.random_string', length=12, special=false) }}"
    - name: Create scoring engine CSV
      ansible.builtin.file:
        dest: "/tmp/{{ passwordlistfile }}"
        mode: '0644'
        state: touch

    - name: Loop through users, change passwords
      ansible.builtin.include_tasks:
        file: tasks/change_passwords.yml
      loop: "{{ passwd.ansible_facts.getent_passwd | dict2items | map(attribute='key') | list }}"
    - name: Fetch passwordlist
      ansible.builtin.fetch:
        src: "/tmp/{{ passwordlistfile }}"
        dest: "{{ playbook_dir }}/passwords/{{ ansible_facts['nodename'] }}/passwordlist.csv"
        flat: true
    - name: Delete passwordlist
      ansible.builtin.file:
        path: "/tmp/{{ passwordlistfile }}"
        state: absent




- name: Control who is admin
  when: users_admins | length > 0 # Checks if list is non-empty
  become: true
  block:
    - name: Delete everybody from admin groups
      ansible.builtin.include_tasks:
        file: tasks/remove_admins.yml
      loop: "{{ passwd.ansible_facts.getent_passwd | dict2items | map(attribute='key') | list }}"
    - name: Add users to admin groups
      ansible.builtin.include_tasks:
        file: tasks/add_admins.yml
      loop: "{{ users_admins }}"

- name: Control who is admin version 2
  when: users_admins2 | length > 0 # Checks if list is non-empty
  become: true
  block:
    - name: Get which users are part of admin groups
      ansible.builtin.set_fact:
        sudo_users: "{{ ansible_facts.getent_group.sudo[2].split(',') if 'sudo' in ansible_facts.getent_group else [] }}"
        docker_users: "{{ ansible_facts.getent_group.docker[2].split(',') if 'docker' in ansible_facts.getent_group else [] }}"
        wheel_users: "{{ ansible_facts.getent_group.wheel[2].split(',') if 'wheel' in ansible_facts.getent_group else [] }}"
        admin_groups: ["sudo", "docker", "wheel"]
    - name: Concatenate admin groups
      ansible.builtin.set_fact:
        existing_admin_users: "{{ sudo_users | union(docker_users) | union(wheel_users) | list }}"
    - name: List existing admin users
      ansible.builtin.debug:
        var: existing_admin_users
    - name: Print only who is supposed to be an admin user
      ansible.builtin.debug:
        msg: "{{ existing_admin_users | difference(users_admins2) }}"
    - name: Loop through admins, remove irrelevant one's from admin groups
      ansible.builtin.include_tasks:
        file: tasks/admins.yml
      loop: "{{ existing_admin_users | difference(users_admins2) }}"
    - name: Get real admins
      ansible.builtin.set_fact:
        existing_admin_groups: 
    - name: Ensure admins are admins
      ansible.builtin.include_tasks:
        file: tasks/add_admins2.yml
      loop: "{{ users_admins2 }}"
