---


# TODO: Only have it generate passwords for users that already have a password, right now it generates for every users
- name: Shuffle passwd user passwords
  become: true
  when: users_passwords_shuffle
  block:
    - name: Get human users
      ansible.builtin.getent:
        database: passwd
      register: passwd

    # Parse this to only do human users or something because this sucks. 

    - name: Create scoring engine CSV
      ansible.builtin.file:
        dest: "/tmp/passwordlist.csv"
        mode: '0644'
        state: touch

    - name: Loop through users, change passwords
      ansible.builtin.include_tasks:
        file: tasks/change_passwords.yml
      loop: "{{ passwd.ansible_facts.getent_passwd | dict2items | map(attribute='key') | list }}"

    - name: Fetch passwordlist
      ansible.builtin.fetch:
        src: "/tmp/passwordlist.csv"
        dest: "{{ playbook_dir }}/passwords/"
    
    - name: Delete passwordlist
      ansible.builtin.file:
        path: "/tmp/passwordlist.csv"
        state: absent
