---
- name: Playbook for testing webserver related roles
  hosts: all

  roles:
    - role: "../roles/facts"
    # - role: "../roles/httpd"
    #   vars:
    #     httpd_scan_webshells: true
    #     httpd_scan_directories: ["/var/www/html","/etc/sudoers.d"]
    - role: "../roles/mysql"
      vars:
        mysql_user: root
        mysql_password: Password123!
        mysql_shuffle_passwords: true
        #mysql_backup: true
        mysql_backup_version: "test"
