---
- name: Playbook aimed at debian, to test shuffling the users role
  hosts: all

  tasks:
    - name: Get human users
      become: true
      ansible.builtin.getent:
        database: passwd
      register: passwd

    - name: Get groups
      become: true
      ansible.builtin.getent:
        database: group

    - name: Get which users are part of admin groups
      ansible.builtin.set_fact:
        sudoers: "{{ ansible_facts.getent_group.adm[2].split(',') | list }}"
      #loop: ["sudo","wheel","docker"]
    - name: List users in the groups
      ansible.builtin.debug:
        var: sudoers
  roles:
    # - role: "../roles/backup"
    #   vars:
    #     backup_directories: ["/etc/systemd"]
    # - role: "../roles/users"
    #   vars:
    #     users_admins: ["vagrant","root"]

