---
- name: Playbook for testing podman related roles
  hosts: all

  roles:
    - role: "../roles/facts"
    - role: "../roles/podman"
      vars:
        podman_backup_version: fresh
        podman_user: podmaner
        podman_backup_containers: 
         - alpine_container
