---
- name: Playbook aimed at debian, to test shuffling the users role
  hosts: all
  roles:
    - role: "../roles/facts"
    - role: "../roles/backup"
      vars:
        backup_version: "fresh"
        backup_directories:
          - /etc/systemd/
        # backup_restore:
        #   - /etc/systemd/
    # - role: "../roles/users"
    #   vars:
    #     users_admins: ["vagrant", "root"]

