---
- name: Run command and save output to variable
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Run command and save output to variable
      ansible.builtin.shell: nix-build --quiet --no-out-link '<nixpkgs>' -A openssh
      register: nix_path

    - name: Print output
      ansible.builtin.debug:
        var: nix_path.stdout

    - name: Copy a template file
      ansible.builtin.template:
        src: sshd.service.j2
        dest: ./sshd.service

