---
  - name: Download nix-installer
    ansible.builtin.get_url:
      url: https://github.com/DeterminateSystems/nix-installer/releases/download/v0.14.0/nix-installer-x86_64-linux
      dest: /bin/nix-installer
  - name: Install Nix
    ansible.builtin.shell: "nix-installer install linux --init none --no-confirm"
    register: nix_install_result
    ignore_errors: yes

  # - name: Install Nix
  #   shell: "curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --init none --no-confirm"
  #   register: nix_install_result
  #   ignore_errors: yes  # Allow this command to fail if Nix is already installed

  - name: Add Nixpkgs-unstable channel and update
    shell: "nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs && nix-channel --update"
    when: nix_install_result.failed == false  # Only run if Nix was successfully installed
