---
- name: Provision Ubuntu vm
  become: true  # If you need to run tasks with elevated privileges, such as sudo
  hosts: all
  gather_facts: true

  tasks:
    - name: Set vagrant user password
      ansible.builtin.user:
        name: "vagrant"
        password: "{{ 'vagrant' | password_hash('sha512') }}"
    - name: Set root user password
      ansible.builtin.user:
        name: "root"
        password: "{{ 'vagrant' | password_hash('sha512') }}"
    - name: Configure sshd to accept passwords
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        line: "PasswordAuthentication yes"
        state: present
        backup: true
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
