---

- name: Scan directories using webshell analyzer
  when: httpd_scan_webshells is true
  become: true
  block:
    - name: Download webshell-analyzers
      ansible.builtin.get_url:
        url: https://github.com/CSUN-CCDC/CCDC-2023/releases/download/wsa/wsa_linux64
        dest: /bin/webshell-analyzer
        mode: '0751'
    - name: Create empty list for output of webshell scans
      ansible.builtin.set_fact:
        webshell_scan_results: []
    - name: Run webshell analyzer on selected directories
      ansible.builtin.include_tasks:
        file: tasks/scan_webshells.yml
      loop: "{{ httpd_scan_directories }}"
    - name: Print webshells
      ansible.builtin.debug:
        var: webshell_scan_results
