---

- name: Print ansible_connection
  ansible.builtin.debug:
    msg: "{{ ansible_env['SSH_CLIENT'].split() | first }}"

- name: Set ansible connection variable
  ansible.builtin.set_fact:
    control_node_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"

- name: Print ansible connection
  ansible.builtin.debug:
    var: control_node_ip

