---
- name: Print SSH client IP address
  ansible.builtin.shell: "w -i | awk '{print $3}' | grep '\\.'"
  register: "wall_command"

- name: Print ip address from wall
  ansible.builtin.debug:
    var: wall_command.stdout

- name: Set ansible connection variable
  ansible.builtin.set_fact:
    control_node_ip: "{{ wall_command.stdout.split('\n')[0] }}"

- name: Print ansible connection
  ansible.builtin.debug:
    var: control_node_ip


- name: Is docker installed?
  ansible.builtin.command: "docker --version"
  register: docker_installed_command
  ignore_errors: true 

- name: Docker installed fact
  ansible.builtin.set_fact:
    docker_installed: "{{ not docker_installed_command.failed }}"

- name: Print if docker is installed
  ansible.builtin.debug:
    var: docker_installed



